clearcontainers/tests

.ci/go-lint.sh, Makefile, command.go, log.go
A few small fixes were needed to make gometalinter pass. `make check` can now be used to check the tests code base itself.
=> Add checks from gometalinter

cmd/checkcommits/checkcommits.go
"Found 1 commits" is just awful.
=> checkcommits: Use proper grammar rules in verbose message.

.ci/install_cc_env_ubuntu.sh
Note: I can't really test this as CI isn't activated on this repo and I don't have anything practical to test it.
We're downloading a specific kernel later on, so no need to download the
kernel package.
Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>
=> ci: Don't install CC kernel from the rpm repository

.ci/install_cc_env_ubuntu.sh, .ci/install_clear_image.sh, .ci/install_clear_kernel.sh
Note: I couldn't test this in CI, and these are fairly intrusive changes. At least the 2 individual scripts do work locally.
I decided I wouldn't install clear kernel and images by hand any longer so I split two scripts out of the ci setup script.
```
```
=> Standalone clear image & kernel install scripts

cmd/checkcommits/checkcommits.go
The git checkout on SemaphoreCI systems doesn't include
a "master" branch, so use "origin" instead.
=> checkcommits: Fix for running under SemaphoreCI.

Makefile
with this patch full paths are used to run functional tests
allowing the execution of them from any directory
=> functional: Runs functional tests from any directory

cmd/checkcommits/Makefile
The tests should be run before the binary is installed.
=> checkcommits: Run tests before installing binary.

cmd/checkcommits/README.md
A simple "go get" isn't sufficient: checkcommits needs to be
built using make to ensure the version and commit details are
embedded in the binary.
=> checkcommits: Fix build instructions.

Makefile
"$GOPATH" was being incorrectly specified with a trailing "/src".
=> build: Fix the ginkgo build.

Makefile, cmd/checkcommits/Makefile
Added missing license headers to the Makefiles.
=> build: Add license headers.

.ci/upstart-services/cc-proxy.conf
cc-proxy has replaced the option '-v' with '-log' to specify the log
level therefore this patch updates the upstart service used in the CI
fixes #55
=> ci: fix proxy upstart service

cmd/checkcommits/checkcommits_test.go
TestGetCommitAndBranch() was failing in a CI environment as it was
triggering the CI-detection code.  Unset all CI variables after saving
them for sane test behaviour.
=> checkcommits: Fix tests running in a CI environment.

functional/run_test.go
add test to check if a container can run without a pid file
fixes #62
=> functional: run container without pid file

Makefile
Because we get Semaphore CI hanging sometimes when trying to build everything from a "make localintegration" for the testing of CRI-O, this patch only calls into the test itself, without the need for rebuilding everything.
=> Makefile: Fix Semaphore CI failing because of CRI-O tests

.ci/install_runtime.sh, .ci/lib.sh
Install the runtime with modified defaults to ensure it uses the
expected paths. This requires a few variables to be set that will
override the defaults in the runtimes Makefile along with running
"make -e" to tell make to only set variables if they are not
already set.
This change is required to support:
- https://github.com/clearcontainers/runtime/pull/225.
=> CI: Override runtime build defaults.

Makefile
Removes crio from 'make check', since the tests are
unstable. The tests should be re-added once
https://github.com/clearcontainers/runtime/issues/215
is fixed.
=> Disable crio tests from make check target

.ci/install_runtime.sh
Set further variables required by the runtime build to ensure the
runtime can find the installed shim, proxy and pause bundle.
Also, enable verbose build output to make debugging easier.
Required for https://github.com/clearcontainers/runtime/pull/225.
=> CI: Further fixes for latest runtime build.

.ci/install_runtime.sh
After installing the runtime, run its "cc-check" command to ensure the
system is capable of running Clear Containers.
=> CI: Check if system supports Clear Containers.

Makefile
This patch re-enables the CRI-O tests because they are now fixed by the recent introduction of a specific variable into the bats. By setting the environment variable "CRI_STORAGE", we can now specify which storage driver we want to use.
In case of Semaphore, because it is running Ubuntu 14.04 on a 3.13 kernel, we have to set aufs as the storage driver, otherwise we get some issues using devicemapper.
=> Makefile: Re-enable and fix CRI-O tests on Semaphore CI

.ci/setup_env_ubuntu.sh
Running .`ci/setup.sh` locally failed to build and install nsenter - make a couple of, what should be benign to the CI systems, changes to fix this.
=> 20170626 nsenter builds

.ci/install_crio.sh
On some Ubuntu systems go is not in the root path. Modify
the necessary install_crio.sh make lines sudo invocations to
utilise the go in the users space.
Fixes: #83
=> CI: enable crio builds when no go in root path

.ci/setup_env_ubuntu.sh
packaging keys needed to be added in order to install the dependencies
from obs repository.
Fixes #87
Signed-off-by: Geronimo Orozco <geronimo.orozco@intel.com>
=> CI: Add gpg key from obs repository

.ci/setup_tests.sh, .travis.yml
Add TravisCI support by creating the required ".travis.yml"
configuration file.
Fixes #95.
=> CI: Add TravisCI config file and enable checkcommits

cmd/checkcommits/checkcommits.go
`gocyclo` reported that the complexity of function
`getCommitAndBranch()` in `checkcommits` was 16, whereas
our standard upper-bound is 15.
Refactored to reduce complexity.
Fixes #105.
=> checkcommits: Reduce cyclomatic complexity.

cmd/fetchbranches/CI.go
Fix a typo found by the go static checkers.
Fixes: #100
=> fetchbranches: Fix typo

.gitignore
Add the fetchbranches binary to the .gitignore file.
Fixes #111.
=> gitignore: Ignore fetchbranches binary.

.pullapprove.yml, OWNERS
Add @dlespiau and @grahamwhaley as additional project approvers.
Fixes #116.
=> CI: Add additional project approvers

.ci/install_crio.sh, .ci/setup_env_ubuntu.sh
running the CI behind a proxy ```apt-get``` fails trying to
connect to ubuntu servers since it's unable to resolve
the proxy. To fix this issue the CI should inherit the environment
variables of the calling process hence we should run ```apt-get```
using ```sudo -E```
fixes #139
=> ci: run apt-get using sudo -E

.ci/install_crio.sh, .ci/setup_env_ubuntu.sh
This patch adds some commands to build and install libdevmapper and
btrfs-tools from sources, so that we ensure we get the most recent
version. Indeed, CRI-O needs some pretty recent versions of those
libraries/tools.
Fixes #143
=> .ci: Fix CRI-O build by installing manually libdevmapper and btrfs

.ci/setup_env_ubuntu.sh
git is unable to clone repositories when the url starts with
git:// and it runs behind a proxy
fixes #145
=> ci: fix error cloning repositories behind a proxy

cmd/checkcommits/checkcommits_test.go
Apparently this is 'definately' the most mis-spelled word
in the English language.
Fixes: #130
=> checkcommits: Fix spelling error found by misspell

cmd/emailreport/README.md, cmd/emailreport/example.toml, cmd/emailreport/mail.go, cmd/emailreport/mail_test.go, cmd/emailreport/main.go
This tool reports by email the obtained PnP results from checktool execution, next it will send the results by email.
=> metrics: Add PnP failure Report tool

.ci/run_fetch_branches_tool.sh
Build and run the fetch branches tool as part of the setup.sh
of the .ci.
Fixes #121
=> ci: Add the fetch branches tool to CI

.ci/setup.sh
run_fetch_branches_tool is designed to run successfully
only for testing PRs. Adding a validation to run only when
env variable "PULL_REQUEST_NUMBER" exists.
Fixes #156.
=> CI: execute run_fetch_branches_tool only when testing a PR

cmd/fetchbranches/README.md
This README will help to the user to understand of how to use
the fetch branches tool as well as it will provide a description
of the validation tags that should be used to run this tool.
Fixes #107
=> docs: Add README for the fetch branches tool

metrics/run_all_metrics.sh
Add SCRIPT_PATH to run_all_metrics.sh script so it can execute
tests successfully from any location.
Fixes #168
Signed-off-by: Brett T. Warden <brett.t.warden@intel.com>
=> run_all_metrics: detect script path

cmd/localCI/README.rst, cmd/localCI/repo.go
with this patch localCI exports next environment variables
before start a process:
- LOCALCI_PR_NUMBER
fixes #163
=> localCI: add missing environment variables

CONTRIBUTING.md
The repo was missing a CONTRIBUTING file, so add one.
Fixes: #154
=> docs: Add a CONTRIBUTING file

cmd/checkcommits/checkcommits.go
Running checkcommits without --need-fixes still tries to invoke
the FixesPattern regex (that has not been configured), and results
in NULL deref crash.
Gaurd the FixesPattern regex invocation in a conf.NeedFixes check
Fixes: #147
=> checkcommits: Do not do Fixes check unless requested

cmd/localCI/github.go
running as a systemd service git is not able to
read the ~/.gitconfig file therefore this patch adds
a default account identity to avoid errors running the
git command
fixes #191
=> localCI: set default account identity

cmd/localCI/pullRequest.go, cmd/localCI/repo.go
in order to make the logs generated in each testing stage
this patch change the mode of the log directory to 0755 and
the mode of the log files to 0664
fixes #197
=> localCI: make the logs generated in each stage accesible

.ci/setup_env_ubuntu.sh
There is a pull request on the runtime repository which introduces
the support for the machine type q35 for qemu. We need to install
this specific binary that we build from source on our CI environment.
Fixes #198
=> .ci: Install qemu Q35 from sources

.ci/setup_env_ubuntu.sh
The path where q35 is installed is not compliant with the one expected
by the build, meaning that tests with q35 machine type are failing
because the binary cannot be found.
Fixes #206
=> .ci: Install q35 at /usr/bin instead of /usr/local/bin

.pullapprove.yml
We now have multiple sub-projects that have their own vendor
trees with .md files in them we do not want docs review to happen
for (as they are out of our control). Thus, exclude all vendor dirs
through the whole tree for .md file review.
Fixes: #209
=> CI: exclude all vendor/*.md's from pullaprove

integration/docker/inspect_test.go
This will test the docker inspect option as part of the integration tests
Fixes #218
=> tests: Add docker inspect test

.ci/setup_env_ubuntu.sh
All the releases are stored at a different path than the one we
had in our script, and this patch will allow us to avoid our CI
to be broken.
Fixes #229
=> .ci: Use a different path to download devicemapper version

metrics/lib/common.bash
Adds a helper function to the metrics common library to extract the qemu
path from "cc-runtime cc-env" or configuration files at runtime. This
allows several of the network metrics tests to be converted to static
scripts instead of generated via autotools.
Fixes #190
Signed-off-by: Brett T. Warden <brett.t.warden@intel.com>
=> common: implement helper function to find qemu

metrics/run_all_metrics.sh
Environment variable RUNTIME must be defined before running this test.
Verify that it's set to an integer that's greater than zero.
Fixes #172
Signed-off-by: Brett T. Warden <brett.t.warden@intel.com>
=> run_all_metrics: Check value of RUNTIME

container.go, functional/exec_test.go, functional/run_test.go
We are submitting patches to the runtime repository in order to
fix the behavior of the exec command, but we were missing some
tests to validate those expected behaviors.
This patch adds some testing of the exec command when it is
either started "attached" or "detached" from the shell.
Fixes #171
=> functional: Implement standalone testing of the exec command

.ci/setup_env_ubuntu.sh
CRI-O is now relying on a new library called libostree and there is
no Ubuntu packages available before Ubuntu 16.10. Because Semaphore
runs on Ubuntu 14.04, we need to install this library from sources.
Fixes #250
=> .ci: Fix Semaphore CI build by installing libostree from sources

.ci/install_crio.sh, test-versions.txt
crio updates has been updated frecuently and
break our ci. Lets add a lock version.
This version could be used for CC 3.0
release notes.
Fixes: #258
=> ci: add test-versions.txt

cmd/localCI/repo.go
do not try to test a pull request immediately after an error
fixes #264
=> localCI: sleep on error

cmd/localCI/Makefile
make clean rule was not removing the auto generated source
files. Let's do that, to really be clean.
=> localCI: remove generated files when make cleaning

cmd/localCI/github.go
in the case that we do not know if a pull request is mergeable
localCI should not fail, we can just test the pull request
fixes #300
=> localCI: do not fail if we don't know if the pr is mergeable

integration/docker/logs_test.go
Integration docker logs tests should use common function of
runDockerCommand.
Fixes #302
=> tests: Fix docker logs test to use common function

integration/docker/env_test.go
This will check the path, hostname and home of a container
Fixes #294
=> test: Check env in a container

.ci/setup_env_ubuntu.sh
To be able to properly build libostree, we now need to install
a new dependency called libarchive-dev.
Fixes #304
=> build: Fix libostree build

.ci/run_fetch_branches_tool.sh
As localCI overrides GOPATH, it does not find
the fecth tool source code, this commit verifies
if the source code of fetch tools exists in the
new GOPATH, or if it is necessary to get the
source code.
Fixes: #308
=> CI: Fix fetch tool internal source code path

metrics/time/docker_workload_time.sh
The terminal/interactive modes fail during the
execution of docker workload time test by localCI,
it shows: “the input device is not a TTY”.
This commit remove these options mode.
Fixes: #314
=> metrics: fix docker mode execution

.ci/setup_env_ubuntu.sh
This is required to compile the agent which now listens
for certain udev events.
Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>
=> ci: Add libudev-dev dependency

cmd/checkmetrics/Makefile, cmd/checkmetrics/README.md, cmd/checkmetrics/baseline/checkmetrics.toml, cmd/checkmetrics/main.go
If the the baseline file path is not specified by command line, checkmetrics tool will look for the baseline file in a system path by default. This baseline file will be shipped during installation step.
=> Add support for getting baseline file from default path 

integration/docker/user_test.go
Add integration docker user test to run a container as a root and
non-root user.
Fixes #386
=> tests: Add docker user test

.ci/ciao_down_run.sh, .ci/ciao_down_setup.sh, .ci/ciao_down_teardown.sh, .ci/data/cc3-ubuntu-xenial.yaml, .ci/setup_env_ubuntu.sh, test-versions.txt
This commit includes a yaml file with the configuration to start
an ubuntu 16.04 environment with the required dependencies for
building and testing Clear Containers 3.0.
There is also a script called `ciao_down_setup.sh` which will
create the environment.
Fixes #223.
Fixes #246.
=> CI: Add scripts to launch a ciao-down environment

integration/docker/export_test.go
add a close file verification as well as a verification that
the file is a regular file for the integration docker export test
Fixes #343
=> tests: add file close verification to docker export test

.ci/setup.sh
Recently, we have seen a lot of hangs during our CI. This is due to
the low memory available inside the Semaphore box, after we run our
setup. That's the reason why this patch drop all the caches at the
end of the setup, freeing a large amount of memory. This allows our
tests to run properly with the right amount of memory.
For information, I have found that after the setup, the free memory
was around 800MiB out of the 4GiB available on the box. Notice that
when the box is started, there is 1.5GiB already used, meaning that
we really have 2.5GiB available.
Fixes #326
=> .ci: Fix Semaphore CI hangs

cmd/localCI/pullRequest.go
with this patch localCI will not try to post
empty messages in the pull requests
fixes #331
=>  localCI: do not try to post empty messages

.ci/install_clear_kernel.sh, .ci/setup_env_ubuntu.sh
We're going to need vmlinuz to be able to switch to "pc" machine
type for our Qemu hypervisor.
Fixes #354
=> .ci: Install vmlinuz alongside vmlinux

docker.go, integration/docker/restart_test.go
ContainerStop will stop a specific container using a
timeout of 15 seconds, this is because docker stop takes
a lot of time stopping a container
fixes #360
=> integration/docker: implement ContainerStop

cmd/localCI/branch.go
with this patch localCI will not run empty stages
an empty stage does not contain commands
fixes #332
=> localCI: do not try to run empty stages

docker.go, integration/docker/kill_test.go, integration/docker/restart_test.go
Add ContainerRunning function to inspect if a container is running.
Fixes #361
=> tests: Add ContainerRunning function

cmd/emailreport/main.go
emailreport tool fails when it uses checkmetrics
tool for parsing data and sent it by email,
this commit fixes the correct format of checkmetrics
command parameters.
Fixes: #345
=> emailreport: Fix checkmetrics execution tool

cmd/localCI/repo.go
since we are using format characters (%s, %d) we have to use
the format version of warn (warnf)
fixes #348
=> localCI: use warnf not warn

cmd/localCI/github.go
To avoid crashes objects returned by go-gihub API must be
validated before use them
fixes #212
=> localCI: validate go-github variables before use them

command.go, container.go, docker.go, functional/commands_test.go, functional/exec_test.go, functional/options_test.go, functional/run_test.go, integration/docker/attach_test.go, integration/docker/commit_test.go, integration/docker/cp_test.go, integration/docker/create_test.go, integration/docker/env_test.go, integration/docker/exec_test.go, integration/docker/export_test.go, integration/docker/inspect_test.go, integration/docker/kill_test.go, integration/docker/load_test.go, integration/docker/logs_test.go, integration/docker/main_test.go, integration/docker/port_test.go, integration/docker/restart_test.go, integration/docker/run_test.go, integration/docker/tag_test.go, integration/docker/terminal_test.go, integration/docker/user_test.go, integration/docker/volume_test.go
with this wrapper make tests will be easier because the user
will not be worry about the timeouts neither writing incorrectly
the name of the commands
Fixes #374
=>  tests: create a wrapper for docker commands

container.go
this patch uses the function IsVMRunning that is defined in vm.go
to detect if a VM is running and remove the method container.isVmRunning
hece it is no more needed
fixes #384
=> functional: fix container.Exist method

vm.go
to avoid crashes in IsVMRunning function we shouldn't use
the reference to FileInfo that filepath.Walk provides
fixes #396
=> tests: fix IsVMRunning function

cmd/localCI/main.go
according with https://github.com/golang/go/wiki/CommonMistakes
the proper way to start go routines in a loop is:
```
for val := range values {
go func(val interface{}) {
fmt.Println(val)
}(val)
}
```
this patch fixes the main.loop method to avoid issues starting
go routines
fixes #389
=> localCI: use the proper way to start go routines in a loop

cmd/localCI/cvr.go, cmd/localCI/github.go, cmd/localCI/repo.go
Fetchtool uses LOCALCI_REPO_SLUG var, this var is
set by localCI, then fetchtool expects 2 arguments
after split LOCALCI_REPO_SLUG with “/” as delimiter,
however localCI exports this var with github domain
as extra information.
This commit fixes the correct format var for fetchtool.
Fixes: #394
=> localCI: Fix LOCALCI_REPO_SLUG var format

container.go, functional/exec_test.go, functional/run_test.go
this patch implements container.Teardown function and
removes container.Cleanup function, this function can be
useful in the ```AfterEach``` of each test to ensure the
container is destroyed and no resources are leaked
fixes #397
=> tests: implement container.Teardown function

functional/exec_test.go, functional/run_test.go
in the BeforeEach of each test we have to validate errors
before objects
fixes #398
=> functional: validate errors before objects

cmd/localCI/repo.go
the variable pr inside appendPullRequests was duplicated
fixes #406
=> localCI: do not use duplicate names for variables

docker.go
docker rmi does not involve to the runtime hence
the time used to complete this task does not matter
fixes #404
=> integration: change docker rmi timeout

cmd/localCI/repo.go
In order to free memory localCI must delete from the revisionsTested
map the revisions already closed or merged
fixes #407
=> localCI: remove PRs already closed or merged

functional/exec_test.go
according with https://onsi.github.io/gomega/#making-assertions
we shouldn't use ```Should``` or ```ShouldNot``` with ```Expect```
fixes #399
=> functional: Do not use Should or ShouldNot to make assertions

Dockerfiles/SwarmTest/Dockerfile.nginx, Dockerfiles/SwarmTest/README.md
Add Nginx Dockerfile that enables the ip command that will be
used in swarm integration tests
Fixes #387
=> tests: Add Dockerfile for docker integration swarm tests

.ci/run_metrics_ci.sh
This script execute metrics and uses emailreport
tool in order to send results by email.
Fixes: #347
=> CI: Add script to execute/report metrics

Makefile
The 5 seconds timeout is appropriate if the tests run on baremetal,
but according to recent changes on QEMU parameters if running in a
nested environment, the tests have been slowed down by disabling fast
MMIO access previously performed by virtio 1.0.
And given the fact that our CI runs on a VMM, we cannot afford this
timeout of 5 seconds. Moving this timeout to 15 seconds makes the
tests passing even when run inside a VM.
Fixes #412
=> ci: Increase test timeout from 5 to 15 seconds

metrics/density/docker_memory_usage.sh, metrics/lib/common.bash, metrics/run_all_metrics.sh
Add the PSS memory footprint test to the metrics density subdir.
Derived from https://github.com/01org/cc-oci-runtime/blob/master/tests/metrics/density/docker_memory_usage.sh.in
=> Add density metrics

integration/stability/agent_stability_test.sh
This stability test will run a container and the perform
several execs to that container.
Fixes #421
=> tests: Add docker stability test

test-versions.txt
The new commit of CRI-O has been tested and works well with
Clear Containers.
Fixes #424.
=> ci: update CRI-O version used for testing

integration/docker/load_test.go
Fix docker load test to use docker.go functions like rmi and commit
Fixes #428
=> tests: Fix docker load test to use docker.go functions

integration/docker/main_test.go, integration/docker/user_test.go
this patch re-implements docker user tests to verify
that user, group and additional groups are set correctly
inside the container
Fixes #426
=> integration/docker: re-implement docker user tests

metrics/storage/fio_job.sh
This value was used for CC 2.x, now this value
is not valid for CC3.0 furthermore it is set by
metrics common lib.
Fixes: #430
=> metrics: storage: Remove RUNTIME default value

.ci/lib.sh
If root user does not have go in its $PATH envar, sudo -E make install will fail.
We need to specify the $PATH of the current user with the sudo command, so it finds go.
Fixes #433.
=> CI: Specify PATH in `make install` command to install CC components

docker.go, integration/docker/export_test.go
Add docker export function at docker.go in order to improve
readability in the integration docker tests
Fixes #435
=> tests: Add docker export function at docker.go

docker.go, integration/docker/kill_test.go
this patch re-implement docker kill tests in order to check
all possible signals and its exit codes
fixes #222
=>  integration/docker: re-implement docker kill tests

cmd/localCI/language.go, cmd/localCI/repo.go
localCI re-tests a pull request failed even if it has not
changed (no new commits), this is a wrong behavior because a
pull request must be re-tested only when it has
changed (new commits).
fixes #416
=>  localCI: do not re-test a pull request failed

metrics/network/network-nginx-ab-benchmark.sh
This network test should stop if there is an
error exit code during execution, this commit
enables "-e", furthermore it fixes command
exist validation in order to finish correctly
in case of missing dependencies.
Fixes: #440
=> metrics: network: Fix execution mode

integration/docker_popular_images/popular_docker_images.bats
Change the configuration file for the kong test of the most popular
images from Docker Hub.
Fixes #444
=> tests: Fix kong test at the docker popular images test

docker.go, integration/docker/swarm_test.go
Add integration docker swarm test to check eth0 and eth1 interfaces
Fixes #386
=> tests: Add docker swarm test to check interfaces

docker.go, integration/docker/network_test.go
Add docker network functionality at docker.go in order to improve
readability and maintenance to integration tests.
Fixes #446
=> tests: Add docker network functionality to docker.go

metrics/lib/send_results.sh
Due to the paths/names of the runtime binaries are
mixed, it is not possible to get the version of the
runtime used, this commit fixes that.
Fixes: #438
=> metrics: Fix the path/name of the runtime used

.ci/data/crio.service, .ci/install_crio.sh, .ci/setup_env_ubuntu.sh, integration/kubernetes/cleanup_env.sh, integration/kubernetes/data/kube-flannel-rbac.yml, integration/kubernetes/data/kube-flannel.yml, integration/kubernetes/init.sh, integration/kubernetes/lib.sh, integration/kubernetes/nginx.bats, integration/kubernetes/setup.sh
This PR:
1. updates the CRI-O configuration to support kubernetes.
2. Install Kubernetes and its dependencies 
3. Configures kubernetes to use CRI-O with clear containers for untrusted workloads
=> kubernetes: Add setup, init scripts and nginx test

integration/docker/restart_test.go
Implement DockerRun function from docker.go at the restart test
Fixes #456
=> tests: add DockerRun function to restart test

integration/docker/terminal_test.go
Instead of using runDockerCommand change to DockerRun function implemented at
docker.go
Fixes #452
=> tests: Add DockerRun function to terminal test

cmd/localCI/repo.go
this patch sets log directory in the stage config before
run the stages
fixes #460
=> localCI: fix running as a systemd service

integration/docker/export_test.go, integration/docker/inspect_test.go, integration/docker/load_test.go, integration/docker/logs_test.go, integration/docker/port_test.go
Use DockerRun function at integration tests like port, logs, load, inspect, export
Fixes #458
=> tests: Implement DockerRun function at integration tests

cmd/localCI/repo.go
with this patch localCI honours the whitelist of
users whose pull requests can be tested
fixes #463
=> localCI: honour whitelist

metrics/run_all_metrics.sh
These basic cases use a similar configuration (block size, ioengine etc),
but using different operations:
- Linear read
- Linear write
- Random read
- Random write
Fixes: #466
=> metrics: Add IO storage metrics to run_all_metrics

cmd/localCI/github.go, cmd/localCI/repo.go
this patch increases timeout used to request data from
github server, also if the list of revisions is empty
the list of revisions tested is not updated to avoid
localCI re-tests pull requests already tested
fixes #468
=> localCI: don't re-test a PR if its hash doesn't change

metrics/network/network-nginx-ab-benchmark.sh
This metrics test should use RUNTIME var in order to be executed
using a different runtime. This commit adds that.
Fixes: #473
=> metrics: network: allow to specify another runtime

metrics/run_all_metrics.sh
The "all" metrics tests execution is interrupted for
errors related to commands/tools dependencies, it is
better to ask them before execution. This might seem
redundant due to these dependencies could be requested
by each metrics test, however this allows to avoid
this kind of interruption/errors running metrics test
as a group or running an independent test.
Fixes: #471
=> metrics: Verify dependencies before execute all

metrics/network/network-metrics-cpu-consumption.sh
This metrics test just allow measure the cpu % about Clear Containers,
it fails when tries to measure CPU % of components that only exists in
during a Clear container execution (e.g. qemu instance).
This commit allows to measure the CPU % of a  workload launched by a
runc container.
Fixes: #488
=> [RFC]: metrics: network: measure CPU % of runc containers

metrics/run_all_metrics.sh
The storage metrics storage tests should be executed using
SCRIPT_PATH var which has the absolute path, this commit
adds that missing var.
Fixes: #482
=> metrics: all: Add missing path var

.ci/setup_env_ubuntu.sh
We don't need to build the branch 2.9.0 of q35-lite since it is not
used. Moreover, even if we decide to switch to q35-lite in a near
future, we will rely on the packaged version.
Fixes #495
=> .ci: Don't build q35-lite from sources

.ci/install_runtime.sh
This commit cleans up the installation of Docker service for Clear
Containers. It also fixes the dockerd command line having some issues
if using -D flag on latest Docker version 17.06.
Fixes #499
=> .ci: Fix and clean runtime installation

.ci/setup.sh, .ci/setup_env_fedora.sh
With this changes, the CI scripts will be able to detect if the setup is being run on Fedora or Ubuntu.
=> CI: Add Fedora support

metrics/network/network-metrics-cpu-consumption.sh
This script fails due to a container is already using
the same name. This happens because it does not clean the environment
before to run the tool/test. This commit adds a common function
in order to clean up the current containers running.
Fixes: #497
=> metrics: network: Fix conflict of container already in use

cmd/emailreport/README.md, cmd/emailreport/mail.go, cmd/emailreport/main.go
These commits allow to notify the results of checmetrics execution by email even if  it fails, furthermore a commit adds the "comments" option in order to show more information about an event.
=> cmd: emailreport: Notify results status

.ci/install_crio.sh, integration/kubernetes/setup.sh, integration/openshift/README.md, integration/openshift/data/hello-pod-cc.json, integration/openshift/hello_world.bats, integration/openshift/init.sh, integration/openshift/openshiftrc, integration/openshift/setup.sh, test-versions.txt
This commit adds scripts to setup the environment for running OpenShift on top of Clear Containers, initialize the nodes and run a simple Connectivity test.
Fixes #465.
=> Add Openshift setup and test

.ci/install_qemu_lite.sh, .ci/setup_env_ubuntu.sh, test-versions.txt
This change install clear-containers-image, linux-container and
qemu-lite packages from download.clearlinux.org using `alien` as
the packages in the site are RPM.
This change is to not rely on OBS platform as sometimes the service
is down.
Fixes #513.
=> CI: Install packages from clearlinux.org instead of OBS

integration/kubernetes/init.sh, integration/kubernetes/nginx.bats
The nginx test has a timeout for launching the workload, as
the required images are downloaded at that time, sometimes the
test fails because of the timeout. To prevent the failure, this fix pulls the
image before launching the workload.
Also when initializing the kubernetes services, including the
dns pod, sometimes it is not enough 60 seconds to pull all images
and start the services, then, this also increases the timeout of
the initialization to 180 secs.
Fixes #511.
=> kubernetes: pull images before launching workload

.ci/teardown.sh
teardown.sh will collect the log files from the cc-proxy,
cc-runtime and cri-o.
Fixes #515.
=> CI: Add teardown script to collect log files

.ci/setup_env_ubuntu.sh
This commit adds "16.10" as a valid verison ID in order
to install the Clear Containers kernel image.
Fixes: #519
=> ci: allow to install kernel image in ubuntu 16.10

metrics/network/network-metrics-iperf3.sh
This script fails due to a container is already using
the same name. This happens because it does not clean
the environment before to run the tool/test. This commit
uses a common function in order to clean up the current
containers running.
=> metrics: network: Fix dirty environment

.ci/install_runtime.sh
The setup of Clear Containers uses a systemd var in order to
include the path of the runtime, the metrics tests do not work
due to they expect “cc-runtime” as name. This commits rename
cc30 var by cc-runtime.
=> [RFC]: ci: Rename systemd var for runtime

.ci/install_crio.sh, integration/cri-o/crio.bats, test-versions.txt
Today we hit an issue of how CRI-O handle container images.
https://github.com/kubernetes-incubator/cri-o/issues/902
A fix from CRI-O has been released and we need to update to
that version.
Since we rely on their test/helpers.bash script to run our
tests, and as that script now uses crictl (from cri-tools repo),
this change also installs crictl binary.
Fixes #530.
=> CI: update sha version of CRI-O to fix integration tests

integration/docker/kill_test.go
We have to let the container start and process the trap before
sending it the expected signal.
Fixes #534
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
=> kill: Sleep before sending a signal

.ci/install_runtime.sh
Using ci automation, docker cannot pull images,
this is due to the system could use proxy. this
commits adds the proxy if the system has set the
variables http_proxy and https_proxy.
Fixes: #528
=> [RFC] ci: Add proxy to systemd docker unit

metrics/run_all_metrics.sh
This commits allows to run just a certain group of tests, however
if no option is specified, it will run all metrics tests by default.
Fixes: #532
=> metrics: run only a group of tests

.ci/install_runtime.sh
If the new runtime config file exists, use it over the legacy version
(which is deleted for safety).
Fixes #542.
=> CI: Use new runtime config if available

.ci/install_runtime.sh
PR #543 attempted to make the tests use the new runtime config file, but
the fix was incorrect due to a silly typo.
Really fixes #542.
=> CI: Fix typo stopping new runtime config being used

.ci/install_runtime.sh
It appears that in a jenkins environment the new runtime configuration
file is unreadable by a non-root user so elevate privileges when
checking for its existence.
Fixes #547.
=> CI: Really really use new runtime config file

.ci/install_runtime.sh
The ".ci/install_runtime.sh" script was trying to switch to using the
new config file before the runtime was installed (and hence before the
config file could have existed).
Fixes #551.
=> CI: Only check new runtime config file after installation

.ci/setup_tests.sh, .travis.yml
Remove travis CI from tests repo since we want to rely only on
Jenkins CI.
Fixes #554
=> .ci: Remove travis

metrics/network/lib/network-test-common.bash, metrics/network/network-metrics-iperf3.sh
This commit allows access to iperf test
execution using runc.
Fixes: #523
=> metrics: network: Fix docker access

.ci/data/cc-proxy.conf.noksm, .ci/install_proxy.sh
When running under the metrics CI system we do not want the proxy
auto-modifying the KSM modes - we control those from the CI to ensure
we know exactly what we are testing and to get steady state results.
Modify the .ci proxy install script so that it adds the correct
argument to the sytemd file, or copies the correct (added in this
PR) upstart file into place.
Fixes: #559
=> ci: install_proxy: disable proxy ksm mode if on metrics CI

.ci/run_metrics_ci.sh
The metrics ci script should not have to be run as root, as it uses
sudo to raise privs when necessary - but, it invokes a 'make install'
if there are missing commands, and that needs privs to install into
the default system dir paths. Add the relevant `sudo`.
Fixes: #569
=> ci: metrics: run 'make install' with raised privs

integration/openshift/hello_world.bats, integration/openshift/init.sh, integration/openshift/setup.sh
This PR contains three commits that fix the Openshift tests.
- Specify `cgroupfs` as the `cgroup-driver` that kubelet will use.
- Call `cc-runtime` using full path.
- Add message when openshift finishes successfully
=> Openshift: fix tests

.ci/setup_env_fedora.sh, Makefile
This PR fixes a few things so that we can have Fedora support enabled in our Jenkins CI.
Fixes #576
=> ci: Enable Fedora in our Jenkins CI

.ci/jenkins_job_build.sh, .ci/run.sh
All jenkins jobs are very similar since they end up calling into
setup.sh and run.sh. This commit introduces a script that can be
shared across all those jobs/repos.
Fixes #583
=> .ci: Add shared script for Jenkins jobs

docker.go, integration/docker/create_test.go
Creates a container in --read-only and then tries to write
the filesystem.
Fixes #567
=> tests: Add docker create --read-only test

cmd/localCI/github.go
when a pull request is downloaded a new branch is created
the name of that branch MUST be unique to avoid clashes with
already existing branches in the repository under test
fixes #592
=> localCI: fix branch name clash

integration/openshift/setup.sh, test-versions.txt
This change reduces the time for testing the OpenShift integration.
Instead of clonning the repository and build everything with sources,
we download the binaries they provide in their releases.
Fixes #587.
=> openshift: Download binaries instead of building them

docker.go, integration/docker/pause_test.go
This will add the docker integration test for the pause
and unpause commands
Fixes #585
=> tests: Add pause and unpause integration tests

README.md
This commit adds the Fedora 26 build badge and fixes the links
to the ubuntu badges.
Fixes #594.
=> readme: Add Fedora 26 build badge and update existing ones

.ci/openshift_setup.sh, .ci/run.sh, .ci/setup.sh, Makefile, integration/openshift/hello_world.bats
This change will allow to setup Openshift environment and execute tests 
through the CI if envar OPENSHIFT_CI=true. The purpose of this change is
to make minimal changes in our jenkins setup.
=> ci: integrate OpenShift setup and test execution into the CI process 

.ci/openshift_setup.sh, .ci/run.sh, .ci/setup.sh
Instead of having a separate job for testing OpenShift, lets
run them after the integration and CRI-O tests.
Fixes #598.
=> CI: Run openshift along with the other tests

.ci/install_runtime.sh, container.go
The runtime is about to lose its old `--debug` command-line option [*]
which is being replaced by a config file option.
Remove occurences of `--debug` and enable debug for *all* components
specified in the runtime config file.
Fixes #600.
[*] - https://github.com/clearcontainers/runtime/pull/693
=> CI: Enable full debug in runtime config file

.ci/teardown.sh
Display the shim log messages at the end of the CI Run.
Fixes #605.
=> CI: Show shim log at end of CI run

integration/stability/soak_parallel_rm.sh
launch a number of containers, and then 'rm -f' them all in one go.
Check we have the right number of 'components' running at each
stage.
Fixes: #490
=> qa: stability: check multi launch and rm stability

.ci/teardown.sh
If a destination directory is provided to the teardown.sh script,
it will now copy the logs instead of displaying them through the
standard output. By default, if no path is provided, we keep the
original behavior, meaning we're dumping the logs.
Also, because our CI is not testing on Ubuntu 14.04 anymore,
there is no reason for keeping the upstart case handled by our
scripts.
Fixes #608
=> .ci: Copy logs instead of displaying them

.ci/install_crio.sh, test-versions.txt
Currently we test kubernetes with latest runc, but today the
compatibility with CRI-O got broken. This fix adds a
runc_version to ensure we have working builds.
Fixes: #615.
=> ci: Fix kubernetes tests by not testing with runc master

.ci/run_metrics_ci.sh, metrics/lib/common.bash, metrics/run_all_metrics.sh
Rather than doing a systemctl restart on docker and the proxy
for every test invocation, lets just do it the once at the
start before we begin the test cycle.
Fix up the invocation scripts to make the one off call.
Predominanlty because running many frequent restarts on my
ubuntu machine results in systemd disabling docker.service
as it sees it as restarting too often.
Fixes: #619
=> metrics: Only systemctl restart once per cycle

.ci/teardown.sh
In case of Jenkins CI, we need to have log files not too large
so that they can be properly moved from the VM to the Jenkins
server as build artifacts. Also, 5 MiB is a reasonable size to
check those logs from a web browser.
Notice that "sudo" has been removed from this script since none
of them were really needed. Moreover, the copy of the runtime
logs with "sudo" was preventing the regular user to modify the
file previously copied.
Fixes #627
=> .ci: Split log files to avoid getting too large ones

.ci/data/crio.service, integration/kubernetes/nginx.bats, integration/kubernetes/setup.sh, test-versions.txt
Updates kubernetes version used in the tests from 1.6.7 to
1.7.8. 
Jenkins job is not able to open a tty when running this test.
As this test is not required to use a tty, removing -t option
from the kubectl command.
Fixes #563.
=> CI: Update kubernetes to 1.7.8 and execute test without a tty

.ci/install_qemu_lite.sh, .ci/setup_env_fedora.sh, .ci/setup_env_ubuntu.sh
This change install clear-containers-image, linux-container and
qemu-lite packages from download.clearlinux.org.
This change is to not rely on OBS platform as sometimes the service
is down.
Fixes #604
Signed-off-by: Geronimo Orozco <geronimo.orozco@intel.com>
=> CI: Install packages from clearlinux.org instead of OBS (fedora)

metrics/density/docker_memory_usage.sh, metrics/lib/common.bash, metrics/network/network-metrics-iperf3.sh, metrics/network/network-metrics-nuttcp.sh, metrics/network/network-metrics.sh, metrics/network/network-nginx-ab-benchmark.sh, metrics/storage/fio_job.sh, metrics/time/docker_workload_time.sh
Add function and call from init_env to notify which tests we are running when,
and fix up relevant places in tests to set the TEST_NAME var and call init_env as early as practical
in each test.
=> 20171019 clarify logs

Makefile, docker.go, integration/docker/info_test.go
Use CC_RUNTIME variable from Makefile instead of expect
the cc-runtime defined as default runtime in docker.
The PR also  adds two ginkgo options.
- verbose:
Add `-v` option to ginkgo in order to know what commands
are being running on each tests and not only the lines of
ginkgo.
- focus:
Added -fucus option allow to only run some tests.
Example:
```
make integration FOCUS="docker kill"
```
will run only docker kill tests
- Changed `CC_RUNTIME` variable name to `RUNTIME`
Fixes: #637
=> integration: Use docker with user defined runtime

test-versions.txt
We need to update clear-containers rootfs image and the kernel that
is being used in testing.
* Image:
Updated agent with a fix for deadlock
clearcontainers/packaging#158
* Kernel:
Add support for native hot plug
clearcontainers/packaging#133
Fix 9p fs unlink-ftruncate
clearcontainers/packaging#110
=> test-versions: kernel and rootfs image

Azure/cc-setup-azure.sh, Azure/cloud-init.txt
- Use daemon.json to setup the runtime instead of a systemd unit file.
This allows the distro defaults to be preserved.
- Set the default graph driver to devicemapper
- Also ensure that each VM gets its own unique set of disks.
This allows the script to be run multiple times as long as the
VM name is unique
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>
=> Azure: Fixes to docker and crio setup

Azure/cloud-init.txt
- Do not update VM kernel. The current kernel supports nesting
- Install thin provisioning tools prior to docker to ensure that the docker daemon starts up consistently.
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>
=> Azure: Misc bug fixes

metrics/network/network-metrics-iperf3.sh
This commits adds a test that measures the bandwidth
between a client/server interconnection, where
the container takes the role of server and the host
takes the role of client.
Fixes: #617
Signed-off-by: Arevalo, Mario Alfredo C <mario.alfredo.c.arevalo@intel.com>
=> metrics: network: Add host/container test

metrics/storage/fio_job.sh
fio has a lot of things that can be tweaked. Rather than trying
to match script arguments in a 1:1 manner to fio arguments, add
a single 'extra arguments' option so we can pass whatever we need
on to fio.
As an example, this is a typical type of invocation we might use:
```
./storage/fio_job.sh -b 16k -o randread -r cc-runtime -t 'storage IO random read bs 16k' -e libaio -x '--iodepth=1024 --direct=1 --runtime=300 --time_based --ramp_time=60 --invalidate=1'
```
Fixes: #643
=> metrics: storage: Add '-x extra args' arg to fio test

Azure/cc-setup-azure.sh
Some used vars do not have quotes, this commit
adds them.
Signed-off-by: Arevalo, Mario Alfredo C <mario.alfredo.c.arevalo@intel.com>
=> azure: add missing quotes to some vars

.ci/run.sh, Makefile
This commit enables devicemapper for CRIO testing.
Fixes #633
=> .ci: Enable devicemapper for CRIO

.ci/openshift_setup.sh, .ci/setup_env_fedora.sh
install chronic from the moreutils package and use it
in the installation of packages to reduce the log size
generated when running the CI.
=> ci: install chronic on Fedora and use it

docker.go, integration/docker/kill_test.go
Recently, the CI has been failing pretty often when running docker
kill tests. This is due to the way the tests are written. Indeed,
because the exit code is retrieved after a time.Sleep(), it does
not ensure the container has properly exited.
This patch inspects State.Status from the container, that way it
makes sure to retrieve the container exit code only after the
container has exited. With this way to proceed, we will never
read an exit code if it is not ready to be read.
Fixes #658
=> ci: integration: Fix docker kill tests

Makefile
Our CI runs on Azure virtual machines and sometimes a simple docker
command can take some time because of the VM nesting. Let's increase
this timeout to avoid any false failure, which is going to make our
CI more stable.
Fixes #660
=> ci: Allow larger timeout for functional and integration tests

docker.go
We have recently bumped the global timeout from 15s to 60s, and
for all the cases (except docker pull), there is no reason to
apply specific timeouts.
Moreover, this is solving some sporadic issues related to the call
of docker stop. The reason is that docker stop uses SIGTERM first
and after 10s, if the process is still running, it sends SIGHUP.
In both runc and cc-runtime cases, we rely on libcontainer, and
there is a limitation about libcontainer for SIGTERM signal, in
such way that it won't terminate the running process even if the
process receives it.
For those cases, a timeout of 15s for docker stop is too low since
the process has only 5s remaining to really kill and stop everything.
Fixes #664
=> ci: integration: Apply docker timeouts to most tests

cmd/checkmetrics/README.md, cmd/checkmetrics/csv.go, cmd/checkmetrics/main.go
This option allows to parse the metrics CSV files without
a baseline file, the report about these metrics just
includes the mean, the standard deviation and the number
of samples used for those results.
Fixes: #611
=> cmd: checkmetrics: Add nobaseline option

.ci/jenkins_job_build.sh
We had our GOPATH being created/set to our home dir. That worked
fine for short lived Jenkins VMs currently utilised for the QA CI,
but might not be suitable for longer lived Jenkins slaves or ones
that perform parallel runs.
Jenkins provides a defined ${WORKSPACE} for each job - use that
location for GOPATH - which will also give us the benefit of
dropping and cleaning up properly if we ever use the 'remove
workspace after completion' feature of Jenkins.
Fixes: #667
=> ci: jenkins: Use Jenkins workspace for GOPATH

test-versions.txt
This commit updates CRI-O to the new release v1.0.2 for
testing Clear Containers.
Fixes #662.
=> ci: update cri-o version to 1.0.2

metrics/network/network-latency.sh, metrics/network/network-metrics-iperf3.sh, metrics/network/network-metrics-nuttcp.sh, metrics/network/network-metrics.sh
Don't request terminal and interactive (-ti) features from docker
run when they are not requited. Requesting them when run under
'headless' (terminal-less) CI systems makes the tests fail with a
'not a tty' type error.
The tests run fine without these args, the data is returned and the
results files still generated.
Fixes: #671
=> metrics: network: drop -ti docker args

docker.go, integration/docker/restart_test.go
This test introduces some timeouts in order to let the container to
be properly stopped before it tries to restart it. Expected status
might sometimes take some time to be set and we should not error in
case we don't get the expected status on the first try.
Fixes #680
=> ci: integration: Fix docker restart

test-versions.txt
version: 18580
Changes in package systemd (from 234-150 to 234-151):
Auke Kok - Don't crash network-wait-online.
https://download.clearlinux.org/releases/18580/clear/RELEASENOTES
version: 18590
Changes in package systemd (from 234-151 to 234-153):
Arjan van de Ven - version bump from 234-152 to 234-153
Arjan van de Ven - clean up services to be with their binaries
https://download.clearlinux.org/releases/18590/clear/RELEASENOTES
=> versions: Update image to 18770

.ci/jenkins_job_build.sh
Oops, we dropped this, but we do actually need it.
=> Set CI=true in the env for coverage tools

integration/swarm/swarm.bats
Disable swarm test in order to check why is failing randomly.
Fixes #694
=> tests: Disable swarm test

test-versions.txt
Changes:
version: 18800
Changes in package clear-containers-agent (from
1fa147836736824c32a46889d6fb59402d4e58bd-14 to
9adc9d49378aa0a19b85d02c447b3eb1e2b87774-14):
Jose Carlos Venegas Munoz - new agent version 9adc9d
https://download.clearlinux.org/releases/18800/clear/RELEASENOTES
Fixes: #685
=> versions: Update image to version 18860

.ci/teardown.sh
Look in the system log for runtime logs rather than the global log file
(which was removed in https://github.com/clearcontainers/runtime/pull/790).
Fixes #690.
=> CI: Save runtime logs from system journal

.ci/teardown.sh
gzip the CI log file fragments to save space and make downloading
quicker.
Fixes #692.
=> CI: Compress log file fragments

.ci/jenkins_job_build.sh
Because the branch we use is origin/master and not master, the
coveralls report does not get reported to the main page of our
different repos. Basically the information on the badge is not
updated.
We have applied the same thing to our virtcontainers repo.
Fixes #697
=> ci: Fix coveralls report branch

metrics/network/remote_network/README.md, metrics/network/remote_network/remote-networking-iperf3.sh, metrics/network/remote_network/remote-networking-test-common.sh
Add remote bandwidth test using iperf3. Where one host will run
a container that will act as a client and another host will run
a container that will act as a server and bandwidth will be
measure across the containers.
Fixes #673
=> metrics: Add remote iperf3 bandwidth test

integration/swarm/swarm.bats
ci: Fix typo in swarm tests
CI is failing because of a missing '"'.
Fixes #716
=> ci: Fix typo in swarm tests

integration/docker/diff_test.go
integration: docker: Fix diff test by making sure the container runs
The diff test needs to use -i flag in order to keep the container
process running while a "docker exec" is started. This issue was
not visible before because STDIN was never closed on the agent side,
even if it was on the host side. With recent patch from the agent,
this issue got highlighted.
Fixes #705
=> integration: docker: Fix diff test by making sure the container runs

container.go, functional/exec_test.go
functional: Fix exec tests
The functional tests enable terminal=true for exec commands, and at
the same time, they use the old flag --console= without specifying
any path. This leads STDIN to be closed when the command is executed,
and the shim sends this info to the agent, which closes the terminal.
This case should not be testable/acceptable since no terminal is
configured and passed as an argument to the runtime, so that we can
actually use terminal=true for the agent.
This patch forces the use of terminal=false, meaning that STDOUT and
STDERR will still be open to receive the output and it won't cause an
error on the agent.
Fixes #718
=> functional: Fix exec tests

test-versions.txt
- version: 18800
- Changes in package clear-containers-agent (from
1fa147836736824c32a46889d6fb59402d4e58bd-14 to
9adc9d49378aa0a19b85d02c447b3eb1e2b87774-14):
- Jose Carlos Venegas Munoz - new agent version 9adc9d
https://download.clearlinux.org/releases/18800/clear/RELEASENOTES
- version: 19010
- Changes in package systemd (from 234-153 to 234-154):
Miguel Bernal Marin - version bump from 234-153 to 234-154
Victor Rodriguez - Fix CVE-2017-15908
https://download.clearlinux.org/releases/19010/clear/RELEASENOTES
version: 19050
- Changes in package systemd (from 234-154 to 234-157):
- Arjan van de Ven - don't do transient hostnames; we set ours already
- Arjan van de Ven - move vconsole to the console subpackage
https://download.clearlinux.org/releases/19050/clear/RELEASENOTES
- version: …
=> versions: Update Clear Containers image

.ci/install_crio.sh, test-versions.txt
This PR contains 2 commits to update the releases of dependencies we use for testing:
- CRI-O to 1.0.4
- Kubernetes to 1.8.3
=> Update versions: k8s and CRI-O

.ci/jenkins_job_build.sh
When we are running the metrics CI we presume (or have checked)
that the QA tests already work. We do not need to run them again
before we run the metrics CI.
Thus, only run the QA checks when we are not under the METRICS_CI.
Fixes: #710
=> CI: metrics: Jenkins: Do not run QA checks for metrics CI

integration/docker/run_test.go
We should disable hot plug a block device test until the issue
https://github.com/clearcontainers/tests/issues/728 is solved.
Otherwise, we won't be able to merge any of the PR on the agent.
Fixes #729
=> integration: Disable hotplug block device

cmd/localCI/main.go
This commit allows to set a loglevel for
messages output:
Possible options:
- debug
- error (default)
- fatal
- info
- panic
- warn
Fixes: #721
=> localCI: Add loglevels msgs support

metrics/storage/fio_job.sh
Remove the storage images from docker (with --rm) once they have
finished. In particular, these images create large (4G) files when
testing, so consume a lot of space if they are just left around.
Fixes: #726
=> metrics: storage: remove the images after test

metrics/network/remote_network/README.md, metrics/network/remote_network/remote-networking-iperf3.sh
This will measure latency across containers in two different hosts.
Fixes ##732
=> metrics: Add remote networking latency test

metrics/run_all_metrics.sh, metrics/time/README.md, metrics/time/launch_times.sh
The 'docker_workload_time.sh' script measures the round-trip time for
a complete container launch/quit. Whilst this is ueful and lets us
take a single measure to spot regressions in the complete cycle, quite
often we'd like to know more fine-grained times, such as how long it
takes to boot to a payload.
Add a test that takes a number of measures through a run/quit cycle,
and then calculates interesting times from that.
The measures taken here are:
- start time (on host)
- time at execution of payload (`date`)
- timestamp of last `dmesg` entry
- stop time (on host)
From those we calculate:
- time to get to workload
- time to get to the VM kernel
- time to get through VM kernel
- time to quit
- total round-trip time
Fixes: #358
=> metrics: time: Measure 'time to workload', and other relevant times

.ci/jenkins_job_build.sh
cc-runtime cc-check started failing for me - it looks like
if we are not a priv'd user then we need /sbin in our PATH
to find modprobe, or we fail the checks (for vhost enabled
for instance).
Add /sbin to our existing PATH manipulation.
Fixes: #741
=> ci: jenkins: add /sbin to the PATH

metrics/lib/common.bash
We were silently killing stray hypervisors and shim processes, but we were not doing that with `sudo`, so sometimes we would get stray `process not found`errors whilst running the metrics.
Make it now a more blatant warning with some process details, and do the killall with sudo.
It is debatable if we should warn or die here - having stray processes hanging around might be a strong indicator of a bug...
=> metrics: Improve warn and killing of unexpected processes

metrics/network/remote_network/remote-networking-qperf.sh
Add remote UDP and TCP networking latency test using qperf tool.
Fixes #743
=> metrics: Add UDP and TCP networking latency

metrics/network/remote_network/README.md, metrics/network/remote_network/remote-networking-memory-smem.sh, metrics/network/remote_network/remote-networking-test-common.sh
This test will measure RSS memory using smem tool while
running a bandwidth remote network measurement with iperf3.
Fixes #739
=> metrics: Add remote networking RSS memory measurement

.ci/install_crio.sh
We don't need sudo to build cri-o and this leads to having files
owned by root, which is an issue when trying to clean up the
environment.
Fixes: #745.
=> ci: Do not use sudo when building cri-o

test-versions.txt
Allows test for https://github.com/clearcontainers/runtime/pull/835
Fixes: #760
Changes:
version: 19170
Changes in package clear-containers-agent (from 243e2aefa4f9ff5a1bd32967a213e8533dab54df-15 to 04fa18641b046dbcf10d13dcd0715e288bff41ce-16):
Jose Carlos Venegas Munoz - version bump from 04fa18641b046dbcf10d13dcd0715e288bff41ce-15 to 04fa18641b046dbcf10d13dcd0715e288bff41ce-16
Jose Carlos Venegas Munoz - agent: New agent version 04fa18
https://download.clearlinux.org/releases/19170/clear/RELEASENOTES
version: 19180
Changes in package iptables (from 1.6.1-21 to 1.6.1-22):
Arjan van de Ven - version bump from 1.6.1-21 to 1.6.1-22
https://download.clearlinux.org/releases/19180/clear/RELEASENOTES
version: 19200
Changes in package systemd (from 234-157 to 234-158):
Arjan van de Ven - ship …
=> versions: Update image to version 19350

metrics/network/remote_network/remote-networking-iperf3.sh, metrics/network/remote_network/remote-networking-memory-smem.sh, metrics/network/remote_network/remote-networking-qperf.sh, metrics/network/remote_network/remote-networking-test-common.sh
Add the functionality of save_results as well as support runc
in the remote networking tests.
Fixes #754
=> metrics: Add save_results and baremetal support to remote tests

metrics/network/network-latency.sh, metrics/network/network-metrics-nuttcp.sh, metrics/storage/fio_job.sh
A number of the metrics tests do not work under headless (such as some CI systems or running under `nohup`) systems.
Fix up a number of the tests to work (predominantly by not using `-ti` on docker run or trying to use long-running 'shell's to keep a container 'open' (switch to using `tail -f /dev/null`).
=> Fix metrics tests for headless operation

metrics/density/docker_memory_usage.sh, metrics/density/footprint_data.sh, metrics/lib/common.bash, metrics/network/network-latency.sh, metrics/network/network-metrics-cpu-consumption.sh, metrics/network/network-metrics-iperf3.sh, metrics/network/network-metrics-memory-pss-1g.sh, metrics/network/network-metrics-memory-pss.sh, metrics/network/network-metrics-memory-rss-1g.sh, metrics/network/network-metrics-nuttcp.sh, metrics/network/network-metrics.sh, metrics/network/network-nginx-ab-benchmark.sh, metrics/storage/fio_job.sh, metrics/time/docker_workload_time.sh, metrics/time/launch_times.sh
Most of the tests did not check to see if there was an update to the docker images they were using.
Fix this by adding a generic function to do the check, and invoke it from the tests.
=> metrics: update/refresh docker images before running tests

.ci/run_metrics_ci.sh, metrics/network/network-latency-qperf.sh, metrics/run_all_metrics.sh
The ping latency test is quite 'noisy'. Add a qperf based latency test that is better.
For ref - I see maybe 15% noise for ping, and <10% for qperf.
The qperf test also gives a more realistic idea of data latency, rather than the ICMP latency we get from ping.
Will require #773 to land first (as we use the new func call)
=> metrics: add qperf based latency test

.ci/teardown.sh
Now that the cc-proxy will not be a service, we need to use
option -t in journalctl to get the logs from the proxy.
Relates to:
https://github.com/clearcontainers/runtime/pull/835
https://github.com/clearcontainers/proxy/pull/177
Fixes: #775
=> ci: Update how journalctl gets the cc-proxy log

.pullapprove.yml
Instead of listing the users from the documentation team, add the
github documentation team for documentation approval.
Fixes #785.
=> pullapprove: Add documentation team for approval

metrics/lib/common.bash
We use pgrep to report diagnostics on errant processes,
but sometimes those processes have gone by the time we
go looking for them. In that case pgrep fails, but is non
fatal.
Code it as so.
Fixes: #787
=> metrics: common: do not fail if pgrep fails

metrics/network/remote_network/remote-networking-memory-smem.sh, metrics/network/remote_network/remote-networking-test-common.sh
Remove mount commands for iperf3 in remote networking tests.
Fixes #789
=> metrics: Remove mount commands for iperf3.

metrics/network/network-metrics-iperf3.sh
Fix typo in the name of the iperf3 test.
Fixes #797
=> metrics: Fix typo in one of the iperf3 tests.

metrics/network/remote_network/README.md
Update Readme to include how to run the remote-networking-qperf.sh script.
Fixes #795
=> docs: Update Readme for remote networking tests.

.ci/install_proxy.sh
This commit removes legacy code when Clear Containers was relying on
one proxy per host. Now that we rely on one proxy per VM, there is no
point in keeping this.
Fixes #827
=> ci: Remove legacy code related to one proxy per host

cmd/checkmetrics/main.go
The output table data was being printed with 'infinite' precision,
which leads to a very noisy table (like 16+ digits of precision).
Let's make the table more readable (and more likely to fit on an
80 column screen) by setting precision to 3 - we really/rarely need
to see more than that.
Fixes: #824
=> checkmetrics: nobaseline: set precison of output table data

.ci/run.sh, Makefile
Debug why cc-runtime is now woking after swarm test we need to keep checking our PRs move the order of the tests.
Because sometimes an issue can only be reproduced in CI add a function to show cc-runtime logs on error.
Fixes: #835
=> test:Change test order until swarm + openshift issue is fixed.

.ci/README.md, .ci/install_clear_kernel.sh, .ci/install_clearcontainers_kernel.sh, .ci/setup_env_fedora.sh, .ci/setup_env_ubuntu.sh
Instead of pull kernel from Clear Linux rpm use our binaries uploaded to
github.
Fixes: #815
=> ci: pull kernel from github release

metrics/network/README.md, metrics/network/network-metrics-iperf3.sh
Add packet-per-second tests. These tests use UDP with the smallest
packet size to measure the maximum number of packets we can get
through the transports.
The tests measure:
- container to container
- host to container
- container to host (iperf3 Reverse mode)
Fixes: #834
=> metrics: network: iperf3: add pps tests

metrics/network/remote_network/README.md, metrics/network/remote_network/direct-remote-networking-iperf3.sh, metrics/network/remote_network/remote-networking-test-common.sh
This measures network bandwidth using an iperf3 container directly.
Fixes #806
=> metrics: Add remote networking bandwidth test.

cmd/container-manager/manage_ctr_mgr.sh
runtime unit tests require docker to be accessible by the
default user.
Fixes #848.
=> ci: Enable docker for default user

integration/docker/exit_code.go
These tests verify that container gives the correct exit code when
running in interactive and non-interactive mode.
Fixes #846.
=> tests: Add docker exit code tests

integration/swarm/swarm.bats, metrics/lib/common.bash
This will ensure that we have a clean environment before running
swarm tests, also it will ensure to select an interface for
running swarm and finally it will ensure that not processes are
left behind after running swarm test.
Fixes #830
=> tests: Update swarm test to ensure not processes are left behind.

docker.go, integration/docker/privileges_test.go
This test will test the no-new-privileges flag when there is a
change in the /usr/bin/id of a Fedora container.
Fixes #811
=> test: Add docker integration test for no-new-privileges flag.

.ci/run.sh
Add Ubuntu 17.10 to be configured with devicemapper storage
driver for the CI.
Fixes #855.
=> ci: configure devicemapper for cri-o on ubuntu 17.10

cmd/checkmetrics/basefile.go, cmd/checkmetrics/compare.go, cmd/checkmetrics/main.go, cmd/checkmetrics/metric.go
It is useful to know how 'tight' the test checks are - what is the range or width of the 'band of acceptance' that is defined in the toml file.
=> checkmetrics: print out 'acceptance range' info

metrics/network/remote_network/README.md, metrics/network/remote_network/remote-networking-iperf3.sh
This will measure the UDP packet loss for a 64 pkt in order
to obtain an acceptable packet loss.
Fixes #850
=> metrics: Add remote networking packet loss.

cmd/checkcommits/checkcommits.go
Simplify `checkCommitBodyLine()` slightly by creating a new
`commonChecks()` that checks common function argument issues.
Fixes #868.
=> checkcommits: reduce complexity

metrics/README.md, metrics/lib/common.bash
If you have any path characters in the argument to killall
then it will only kill the processes actually using that
binary. Thus, if you have any stuck processes that are using
a different (or previous that has since been replaced) binary,
killall will not find/kill them.
Change the killall to use just the process/file name (with no
path), which means it will kill all processes of that name
(even if they were launched from a binary in a different path)
which may feel a little more 'dangerous', but as we only run
this in reasonably well defined and constrained systems, it
should be fine.
Fixes: #757
=> metrics: killall: do not use the binary path in killall

cmd/checkmetrics/basefile.go
During merge #860, a debug printf snuck in around the Gap
processing.
Drop it.
Fixes: #874
=> checkmetrics: remove accidental debug printf

.ci/jenkins_job_build.sh
Rather than merging the PR commits directly into `master`, create a separate
branch for the PR.
This allows `checkcommits` to determine the changes the PR introduces.
After `checkcommits` has run, merge the PR branch back into `master` since
this is required for coveralls.
Fixes #876.
=> CI: Change handling of git PR branch

.ci/run_metrics_ci.sh, metrics/density/README.md, metrics/density/docker_memory_usage.sh
Previously we were fairly benign about our interactions with KSM - we just turned it on/off and depended on the distro default settings, whilst also hard wiring a sleep (300s) to try and ensure KSM page merging had settled down before taking our measurements.
Let's be a bit smarter by:
- setting some aggressive KSM settings that we define
- actively monitoring KSM to try and spot when it 'settles'
A few benefits fall out of this (on my test system):
- the KSM density test now completes in ~123s, rather than 300s (my original goal)
- the density result is significantly smaller - it would seem 300s was not enough to wait for KSM to really settle!
- the result is more repeatable (CoV of ~0.3 instead of ~0.4 - it was pretty good already, and now it is even better)
=> ci: metrics: improve density tests interaction with KSM

.ci/install_asset.sh
When building an image k8s ci breaks because the user has not
access to docker socket.
Fixes: #882
=> ci: Fix image build  using docker.

.ci/install_asset.sh
SHASUMS file exist in both assets.
To avoid issues when download file from kernel or image
use a tmpdir to download assets.
Fixes: #885
=> ci: install assets use tmpdir

.ci/install_crio.sh, .ci/setup_env_fedora.sh, .ci/setup_env_ubuntu.sh
Instead of get go-md2man from github repository and build
latest version of the tool, install stable version from fedora
and ubuntu packages.
Fixes #892.
=> ci: Add go-md2man, which is cri-o dependency

cmd/container-manager/manage_ctr_mgr.sh
newgrp command was introduced to login into the docker
group and allow a normal user execute the runtime
unit tests which require the use of docker without
root, but this command didn't had the desired effect
on the CI and when running under a terminal it creates
a new bash session, stopping the installation of all
other components. For this reason, lets remove this
command from the docker installation.
Fixes #890.
=> ctr_mgr: Remove newgroup command from installation

.ci/jenkins_job_build.sh
jenkins may use cc-runtime as default runtime.
This is an issue when an image need to be created with osbuilder.
This commit tries to set runc as default runtime. If is not possible
(because docker not installed), the setup will continue.
Fixes: #897
=> ci: Set runc as default runtime for image creation

.ci/install_crio.sh
Before creating a link in the $GOPATH/bin directory,
ensure the directory exists or create it.
Fixes #902.
=> ci: verify GOPATH/bin exists

.ci/install_asset.sh
When install_asset.sh was added it included a wrong logic
removing tmp_dir, fix it to avoid disk space issues.
Fixes: #905
=> ci: Fix clean up logic from install_assets.sh

.ci/install_crio.sh, .ci/jenkins_job_build.sh, integration/cri-o/crio.bats, integration/kubernetes/cleanup_env.sh, integration/kubernetes/init.sh, integration/kubernetes/nginx.bats, integration/kubernetes/setup.sh, integration/openshift/data/hello-pod-cc.json, integration/openshift/hello_world.bats, integration/openshift/init.sh
Now that we are moving to CRI-O v1.9, the crioctl tool has
been deprecated, instead we need to use crictl for our tests.
Also, k8s v1.9.1 and openshift v3.7.1 changed the configuration slightly.
This PR addresses all issues to be able to move to these newer
versions. 
Depends on: 
Fixes: #867.
=> Update scripts and test to work with latest CRI-O, k8s and openshift

.ci/jenkins_job_build.sh
If jenkins_job_build is called from other repository than
`tests`, the `tests` repo will not be in the $GOPATH tree and
the `manage_ctr_mgr,sh` call will not work. For that reason, we
need to clone tests repo using `go get`.
Fixes #914.
=> ci: clone tests repo on jenkins_job_build.sh

.ci/install_proxy.sh
If running under the metrics CI, then we want to disable the global
KSM control of the proxy, and control it ourselves.
This is effectively an unwind of #828, that was a touch premature.
Fixes: #910
=> ci: metrics: disable ksm on global proxy if under metrics

.ci/install_ksm_throttler.sh
install_ksm_throttler.sh installs the ksm throttler tool,
starts and enables the service on systems that are not
running the metrics CI and stops/disable the cc-proxy
service, in case it is still shipped in the system.
Fixes #913.
=> CI: Install ksm-throttler tool for CI

.ci/run_metrics_ci.sh, metrics/network/README.md, metrics/network/network-metrics-iperf3.sh
Refine our metrics CI invocations somewhat:
- stop running tests that we don't currently check the results for
- refine the iperf3 test run to only test what we do check
- which involved adding a commandline to the iperf3 test so we could tweak it
=> Refine metrics CI invocations

cmd/set_dma_latency/Makefile, cmd/set_dma_latency/README.md, cmd/set_dma_latency/main.go
Add a tool that can be used to set the required dma latency
(in microseconds). This too is particularly useful for
stabilising a system during metrics measurements, as setting
a requirement of 0us disables C and P state transitions (and
effectively pins us to C0).
Fixes: #899
=> cmds: set_dma_latency: Add tool to set dma latency

.ci/install_crio.sh, Makefile, integration/cri-o/crio.bats, integration/cri-o/init.sh, integration/kubernetes/init.sh, integration/openshift/init.sh
This commit entirely relies on the latest version of CRIO in order
to update the bats properly. This is a simple copy/paste of the tests
we already support, but it updates the content to the latest version.
Fixes #918
=> integration: crio: Update bats to match latest version from CRI-O

integration/stability/soak_parallel_rm.sh
Modify the rm soak test to take into account the current
'one proxy per container' architecture.
Fixes: #925
=> integration: soak: take into account new proxy setup

metrics/storage/fio_job.sh
Currently while running the Fio test creates a volume in the host,
however, the script should remove the volume at the end of the test.
Fixes #930
=> metrics: Fix FIO test to remove the volume created

.ci/install_asset.sh
We don't want to call release_image_github.sh using sudo,
as we end up having $GOPATH/bin been owned by root.
As https://github.com/clearcontainers/packaging/pull/277
is now merged, we can remove sudo.
Fixes: #932.
=> CI: call release_image_github.sh script without sudo

integration/stability/soak_parallel_rm.sh
Allow the iterations count to be over-ridden from the
environment.
Also, print out the iterations as 'n of x' as we run.
Fixes: #927
=> stability: soak: allow iterations to be over-ridden

.ci/install_kubernetes.sh, .ci/setup.sh, Makefile, integration/kubernetes/init.sh, integration/kubernetes/nginx.bats, integration/kubernetes/run_kubernetes_tests.sh
With these changes, k8s will be tested with the jenkins
jobs instead of using localCI.
Fixes #928.
=> CI: Integrate Kubernetes testing in the CI flow

integration/docker/run_test.go
containers/virtcontainers#512 introduces new changes in the way CPUs are handled
this patch skips CPU tests to allow containers/virtcontainers#512 get merged.
fixes #937
=> integration/docker: Skip CPU tests

cmd/container-manager/manage_ctr_mgr.sh
Specify storage-driver=overlay2 when changing runtime to runc.
Alsoi when changing runtimes, first stop the service,
remove /var/lib/docker, then change the configuration and
restart the service.
Fixes: #939.
=> manage_ctr_mgr: change the way we switch docker runtimes

integration/kubernetes/run_kubernetes_tests.sh
Add `set -e` to fail if a command does not return
successful.
Fixes: #946.
=> CI: add set -e to run_kubernetes_tests.sh

.ci/install_kubernetes.sh
There is no need to hold the kubernetes packages to
a specific version in the CI. Holding them was preventing
the metrics CI node to fail installing the correct packages.
Fixes: #950
=> CI: do not hold kubernetes packages

metrics/lib/common.bash
We no longer have a global cc proxy systemd service, so do not
try to restart it during metrics system initialisation.
Fixes: #952
=> metrics: do not restart proxy any more

.ci/install_crio.sh
From CRI-O v1.9.8 and above, the manage_network_ns_lifecycle
flag is optional and it is set to 'false'. But for Clear
Containers, we need to setup this flag to true.
Fixes: #958.
=> crio: Set manage_network_ns_lifecycle flag to true

integration/swarm/swarm.bats, metrics/density/docker_memory_usage.sh, metrics/density/footprint_data.sh, metrics/lib/common.bash, metrics/storage/fio_job.sh, metrics/time/launch_times.sh
Whilst we transition metrics over to the kata repos, it will be very helpful to be able to run the metrics here on a kata-runtime.
Add kata-runtime recognition support to the metrics scripts.
=> metrics: add support for kata-runtime

.ci/install_crio.sh
Fix:
- The script does not fetch before checkout.
- It fails if go-md2man symlink already exist.
Fixes: #961
=> ci: prevent cri-o installation script fail.

.ci/run_metrics_ci.sh, metrics/run_all_metrics.sh, metrics/storage/fio_job.sh
Add FIO flags like time_based, drop host pages,
invalidate, direct, etc to produce more stable results.
Fixes #956
=> metrics: Add FIO flags to produce stable results.
