clearcontainers/tests

Makefile
README
README.md
README.rst
command.go
functional/main_test.go
functional/start_test.go

Add some functional tests for start command

Add functional tests for start command 

---

.pullapprove.yml

ci - Add pullapprove config file

ci - Add pullapprove config file

---

.pullapprove.yml
OWNERS

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

OWNERS: Add OWNERS file

---

README.rst

add functional test dependencies and installation instructions

readme: add functional test dependencies

---

command.go
functional/common_test.go
functional/create_test.go
functional/delete_test.go
functional/exec_test.go
functional/kill_test.go
functional/run_test.go
functional/start_test.go
functional/state_test.go

Add functional tests for:
* create
* kill
* delete
* start
* state
* run

Add functional tests

---

.gitignore
Makefile
cmd/checkcommits/README.md
cmd/checkcommits/checkcommits.go
cmd/checkcommits/checkcommits_test.go

Rework of https://github.com/01org/cc-oci-runtime/pull/873 in golang.
By hosting it in the tests repository our other repos can "go get" if
they wish to use it.
Fixes #18.

pkg: Add checkcommits tool.

---

cmd/checkcommits/checkcommits.go

Add a runCommand() function to minimise duplication and ensure
all external commands use the same codepath.

checkcommits: Refactor how commands are run.

---

cmd/checkcommits/checkcommits.go

Explain which branch and commit the tool operates on.

checkcommits: Improve usage wording.

---

cmd/checkcommits/checkcommits.go

Refactor the code to simplify the way git log is called.

checkcommits: Refactor for git log.

---

.ci/install_cc_env_ubuntu.sh
.ci/install_cc_proxy.sh
.ci/install_cc_shim.sh
.ci/upstart-services/cc-proxy.conf

Those installation scripts can be shared accross different project needing one of this component to be properly installed.

ci: Add some generic scripts

---

cmd/checkcommits/checkcommits.go

Previously, the destination branch would be ignored but that was not the
intent (destination is effectively always "master"). Now, the tool
allows the specification of one or more regular expressions to filter
out source (PR) branches which will be ignored (always considered
successful).

checkcommits: Fix handling of ignoring branches.

---

Makefile

This will run the functional tests when a make check is done

Add functional tests for make check

---

functional/common_test.go
functional/delete_test.go
functional/exec_test.go
functional/kill_test.go
functional/start_test.go
functional/state_test.go

Add functional tests to check stderr and exist code of
command running with an inexistent container id

functional: Add functional tests

---

.ci/install_bats.sh
.ci/install_cni_plugins.sh
.ci/install_crio.sh
.ci/setup_env_ubuntu.sh
.ci/upstart-services/crio.conf
Makefile
integration/cri-o/crio.bats

This commit adds tests and CI scripts to verify the
compatibility of Clear Containers with cri-o.

Add CRI-O Tests for Clear Containers

---

README.rst

readme: update README file

---

vm.go

implement function to check if the VM of a container is still running
fixes #69

tests: check if a VM is still running

---

Makefile
metrics/lib/common.bash
metrics/lib/send_results.sh
metrics/run_all_metrics.sh
metrics/time/docker_workload_time.sh

Add the basic metrics framework and the first metrics test.

RFC: metrics: add framework and first metrics test

---

.ci/install_bats.sh

Signed-off-by: Dmitry Voytik <dmitry.voytik@huawei.com>

ci: don't install bats if it's already present

---

integration/cri-o/crio.bats

This patch increases the number of CRI-O tests that should be successful with Clear Containers 3.0.

integration: Add more CRI-O tests

---

cmd/fetchbranches/CI.go
cmd/fetchbranches/CI_test.go
cmd/fetchbranches/SemaphoreCI.go
cmd/fetchbranches/SemaphoreCI_test.go
cmd/fetchbranches/branch.go
cmd/fetchbranches/branch_test.go
cmd/fetchbranches/main.go
cmd/fetchbranches/pr.go

This is the commit of the fetch branches tool that
will be in charge of checking the branch where a pull request
needs to be tested it.
Fixes #77 

Fetch branches tool

---

cmd/fetchbranches/main.go

ci: Fix command line for the fetch of the branch.
Fixes #120

ci: Fix fetch github command

---

cmd/checkcommits/checkcommits_test.go
cmd/fetchbranches/CI.go
cmd/fetchbranches/SemaphoreCI.go
cmd/fetchbranches/SemaphoreCI_test.go
cmd/fetchbranches/main.go

Fix up some items reported by the go static checkers.

checkcommits static checks

---

cmd/checkcommits/README.md
cmd/checkcommits/checkcommits.go

Fix up a few typos found whilst reading/reviewing
Fixes: #133

checkcommits: Fix some typos in README and code

---

cmd/fetchbranches/CI.go
cmd/fetchbranches/CI_test.go
cmd/fetchbranches/localCI.go
cmd/fetchbranches/localCI_test.go

this patch add support for localCI in fetchbranches
fixes #166

fetchbranches: add support for localCI

---

cmd/localCI/README.rst
cmd/localCI/config/configuration.toml
cmd/localCI/logServer.go
cmd/localCI/repo.go

localCI: implement copy logs to server

---

.ci/setup.sh

ci: enable localCI in the continuous integration scripts

---

cmd/localCI/go.go

localCI: creates clone directory before fetch a pr

---

cmd/localCI/repo.go

localCI: append pr number to env vars

---

cmd/emailreport/mail.go
cmd/emailreport/main.go

golint warns about some var naming issues, fix them up.
Fixes: #150

emailreport: fix golint warnings

---

cmd/localCI/github.go

this patch includes git's stderr in the error returned by
downloadPullRequest
fixes #184

localCI: improve message errors when the git command fails

---

cmd/localCI/github.go
cmd/localCI/pullRequest.go

localCI: do not test non-mergeable pull requests

---

functional/main_test.go
functional/options_test.go
functional/run_test.go

This will test global options like help and version
Fixes #195

tests: Add standalone test for global options

---

Makefile
docker.go
integration/docker/main_test.go
integration/docker/run_test.go

add integration test for docker
fixes #70

integration: implement integration tests for docker

---

cmd/localCI/github.go

validates all needed fields of the objects returned by
the pullRequestService before use them
fixes #211

localCI: fix crash getting pull requests

---

cmd/localCI/cvr.go
cmd/localCI/github.go
cmd/localCI/pullRequest.go
cmd/localCI/pullRequest_test.go
cmd/localCI/repo.go

With this patch localCI fetches the branch of the pull request
and then check it out
fixes #220

localCI: checkout the pull request don't merge it

---

functional/options_test.go

Fix issues reported in the tool
Fixes #231

tests: Fix issue in options test static checks

---

integration/docker/inspect_test.go

Check issues reported by static checks
Fixes #232

test: Fix issue of static checks inspect test

---

cmd/localCI/repo.go

this patch strip setup and runTests functions in several functions
in order to reduce the cyclomatic complexities of them and
be in compliance with gocyclo
fixes #233

localCI: fix golang static checks

---

cmd/localCI/pullRequest_test.go

this patch fixes the unit tests of pullRequest.go
fixes #240

localCI: fix unit tests

---

integration/docker/exec_test.go

This will test the docker exec command
Fixes #237

test: Add docker exec integration test

---

integration/docker/port_test.go

Add docker port integration test
Fixes #251

tests: Add docker port test

---

integration/docker/create_test.go

Add integration docker create test
Fixes #248

tests: Add docker create test

---

cmd/localCI/Gopkg.lock
cmd/localCI/vendor/github.com/BurntSushi/toml/COPYING
cmd/localCI/vendor/github.com/BurntSushi/toml/decode_test.go
cmd/localCI/vendor/github.com/BurntSushi/toml/lex.go

vendor update to get new toml license
fixes #203

localCI: vendor update

---

metrics/lib/common.bash
metrics/storage/fio_job.sh

This test measures the bandwidth consumed by a specif I/O
operation (read, write, random-read etc) under certain configuration.
The result is obtained using FIO tool, it runs inside of a container.

metrics: Add I/O storage performance test

---

integration/docker/kill_test.go

Add integration docker kill test
Fixes #254

tests: Add docker kill test

---

.ci/install_runtime.sh

If environment uses systemd, install the correct configuration
file for changing the default runtime in docker, reload the
systemd units and restart docker service.
Fixes #271.

CI: Install systemd file for changing default runtime in docker

---

integration/cri-o/crio.bats

With recent changes brought to the runtime and to hyperstart agent,
we can add two new tests from the CRI-O bats:
- ctr logging [tty=true]
- ctr execsync failure
Fixes #260

integration: crio: Add 2 more tests

---

integration/docker/commit_test.go

Add integration docker commit test
Fixes #274

tests: Add docker commit test

---

cmd/localCI/config.go
cmd/localCI/cvr.go
cmd/localCI/github.go
cmd/localCI/main.go
cmd/localCI/pullRequest.go
cmd/localCI/repo.go

this patch adds more logs and improve the log system
fixes #282

localCI: improve the log system

---

cmd/localCI/README.rst
cmd/localCI/data/configuration.toml
cmd/localCI/go.go
cmd/localCI/language.go
cmd/localCI/repo.go

localCI: remove support for VMs

---

cmd/localCI/repo.go

this patch splits repo setup function in order to
make it easier to read/understand
fixes #286

localCI: split repo setup function

---

integration/docker/logs_test.go

Add integration docker logs test
Fixes #244

tests: Add docker logs test

---

integration/docker/commit_test.go
integration/docker/create_test.go
integration/docker/exec_test.go
integration/docker/inspect_test.go
integration/docker/kill_test.go
integration/docker/main_test.go
integration/docker/port_test.go

Use a common function for runDockerCommand in our integration tests
Fixes #296

tests: Common function for integration docker tests

---

integration/docker/export_test.go

Add integration docker export test
Fixes #276

tests: Add docker export test

---

integration/docker/tag_test.go

Add integration docker tag test
Fixes #292

tests: Add docker tag

---

cmd/localCI/pullRequest.go

localCI: fix crash trying to check a nil comment trigger

---

integration/docker/load_test.go

Add integration docker load test
Fixes #290

tests: Add docker load test

---

integration/docker/terminal_test.go

Add integration docker terminal test that will check
pseudo tty and TERM env.
Fixes #312

tests: Add docker terminal test

---

integration/docker/cp_test.go

Add integration docker cp test
Fixes #306

tests: Add docker cp test

---

integration/docker/attach_test.go

Add integration attach docker test.
Fixes #243

tests: Add attach docker test

---

integration/docker/network_test.go

Add integration docker network test.
Fixes #327

tests: Add docker network test

---

integration/docker/volume_test.go

Add integration docker volume test.
Fixes #335

tests: Add docker volume test

---

cmd/localCI/config.go
cmd/localCI/repo.go

this patch reduce the size of the setup function used
to set default values
fixes #341

localCI: set default values before load configuration

---

integration/docker/restart_test.go

Add integration docker restart test
Fixes #351

tests: Add docker restart test

---

docker.go
integration/docker/main_test.go
integration/docker/user_test.go

pull alpine image before use it to avoid timeouts when
that image is used
fixes #359

 integration/docker: pull alpine image before use it

---

integration/docker_popular_images/README
integration/docker_popular_images/popular_docker_images.bats

This test will run the most popular images at Docker Hub.
Fixes #372

tests: Add popular docker images test

---

cmd/localCI/README.rst
cmd/localCI/config.go
cmd/localCI/console.go
cmd/localCI/repo.go
cmd/localCI/stage.go
cmd/localCI/stage_test.go

allocate a TTY for running stages

Allocate a TTY for running stages

---

metrics/lib/common.bash
metrics/network/lib/network-test-common.bash
metrics/network/network-latency.sh
metrics/run_all_metrics.sh

Move network-latency.sh from wip folder, add it to run_all_metrics.sh.
Fixes #320
Signed-off-by: Brett T. Warden <brett.t.warden@intel.com>

metrics: port network-latency test to CC3.x

---

Dockerfiles/BuildTest/Dockerfile
docker.go
integration/docker/build_test.go

Add integration docker build test
Fixes #378

tests: Add docker build test

---

docker.go
integration/docker/info_test.go

Add integration docker info test
Fixes #227

tests: Add docker info test

---

functional/commands_test.go
functional/run_test.go

this patch replace omega character with Expect to make
tests easier to read and understand
fixes #192

functional: do not use omega character

---

integration/docker_popular_images/README

Change of the name of the script.
Fixes #417

docs: Fix Readme of how to run popular docker hub images script

---

.ci/run_metrics_ci.sh

We don't run all the metrics tests for the metrics CI, but we do
want to run a 'good subset' that covers all key data from all key
areas of interest.
Thus, add memory footprint, network and storage tests to the default
set of metrics we run in the ci.
Fixes: #414

[RFC] metrics: ci: Add more tests to the metrics ci script

---

docker.go
integration/docker/search_test.go

Add integration docker search test.
Fixes #448

tests: Add docker search test

---

docker.go
integration/docker/diff_test.go

Add integration docker diff test
Fixes #450

tests: Add docker diff test

---

integration/docker/tag_test.go

Implement DockerRun and DockerRmi functions at integration tag test
Fixes #454

tests: add DockerRun and DockerRmi to tag test

---

integration/docker_popular_images/popular_docker_images.bats

use asd (aerospike daemon) to verify if aerospike image
is compatible with CC 3.0

integration/popularImages: change aerospike test

---

Makefile

this patch removes duplicated check target
fixes #476

tests: update Makefile check target

---

.ci/install_crio.sh
.ci/setup_env_ubuntu.sh
functional/exec_test.go

Modify scripts to get Jenkins operational.
Fixes #484

.ci: Update CI scripts to make sure it works with Jenkins

---

cmd/localCI/repo.go

with this patch if localCI is not able to get the information
of a specific pull request it uses the old one to avoid deleting
it from already tested revisions causing a re-test of a pull
request that has not changed
fixes #468

localCI: don't re-test if pull request has not changed

---

metrics/density/docker_memory_usage.sh

This metrics test just allow measure the memory density
about Clear Containers, it fails when tries to measure
PSS memory of components that only exists during a Clear
container execution (e.g. qemu instance). This commit
allows to measure the PSS of the workload launched by a
runc container.
Fixes: #480

[RFC]: metrics: density: measure runc containers

---

.ci/setup_env_ubuntu.sh

This commit allows us to setup Clear Containers on a Ubuntu 17.04
environment.
Fixes #504

.ci: Add Ubuntu 17.04 support

---

.ci/run_metrics_ci.sh

This commmit adds the url of the pull request
in the message body of the report.
Fixes: #508

ci: Include PR url in msg body

---

.ci/run_metrics_ci.sh

This commit allows to save the results of each metrics
tests execution inside a backup path.
Fixes: #517

ci: metrics: save results in backup path

---

metrics/README.md

This commit adds a README file with general information
about metrics tests and how to execute them.
Fixes: #538

metrics: update documentation

---

docker.go
integration/docker/main_test.go
integration/docker/user_test.go

integration/docker: enable user and groups test 

---

test-versions.txt

- Agent: new structured log
Fixes: #602
Signed-off-by: Geronimo Orozco <geronimo.orozco@intel.com>

test-versions.txt: Update clear-containers-image

---

metrics/density/docker_memory_usage.sh
metrics/network/network-metrics-memory-pss-1g.sh
metrics/network/network-metrics-memory-pss.sh
metrics/network/network-metrics-memory-rss-1g.sh

We don't need to run the whole metrics scripts as root - let's just invoke sudo when we need to.

20171019 no sudo

---

Azure/README.md
Azure/cc-setup-azure.sh
Azure/cloud-init.txt

These group of commits allow to launch an azure/VM and install all necessary dependencies in order to execute Clear Containers.
Fixes: #623

azure: Add setup for azure/CC

---

test-versions.txt

Update versions to be synchronized with packaging.
Fixes: #647

versions: sync versions with packaging

---

.ci/setup_env_ubuntu.sh

Now that we do not use SemaphoreCI for the CI, we can safely
remove the installation of dependencies used for Ubuntu
14.04.
Fixes #645.

ci: remove installation of ubuntu 14.04 dependencies

---

Azure/cloud-init.txt

These commit adds some minior fixes about
comments.
Signed-off-by: Arevalo, Mario Alfredo C <mario.alfredo.c.arevalo@intel.com>

azure: fix some typos in comments

---

integration/docker/kill_test.go

runc was failing with our kill test.
- Only SIGKILL and SIGSTOP can not be caught, blocked or ignored, skip
signals that are not forwared by cc-shim.
- Show the signal name when running the tests (not only number).
Fixes: #640

kill: Fix kill tests

---

integration/docker/attach_test.go

unskip issue clearcontainers/runtime#363

integration/docker: unskip clearcontainers/runtime#363

---

integration/swarm/swarm.bats

This test retrieves the hostnames from the replicas using swarm.
Fixes #629

tests: Add retrieve hostname from curl test for swarm

---

integration/swarm/swarm.bats

Check MTU interfaces and values using swarm.
Fixes #688

tests: Add MTU test for swarm

---

metrics/network/remote_network/README.md
metrics/network/remote_network/remote-networking-iperf3.sh

Add remote networking jitter test using swarm and iperf3.
Fixes #699

metrics: Add remote networking jitter test

---

integration/swarm/swarm.bats

Disable MTU test for swarm.
Fixes #714

tests: Disable MTU swarm test

---

integration/docker/run_test.go

run a container with --device option and check if the
device is visible inside the container
fixes #675

integration/docker: add hot plug test

---

metrics/network/remote_network/README.md
metrics/network/remote_network/remote-networking-iperf3.sh

This will measure parallel bandwidth (-P4) with swarm and iperf3.
Fixes #712

metrics: Add remote parallel bandwidth test

---

integration/docker/run_test.go

use losetup to create loop devices
fixes #728

integration/docker: fix hot plug test

---

.ci/run_metrics_ci.sh

Depending on which CI system we are running (such as localCI
or Jenkins etc.), we want to use different 'tail end' checks.
Modify the script to check the CI env variables, and do the
appropriate thing.
Note, the 'generic' thing is to use the checkmetrics tool, and
have the config file determined by the name of the host, thus
easily allowing different config files per host (that are not
all called the same thing).
Fixes: #724

ci: metrics: Choose check method according to CI

---

docker.go
integration/docker/package_manager_test.go

this test checks 9p functionality and the compatibility
with debian.
fixes #737

integration/docker: add test to check apt-get

---

integration/docker/env_test.go

check environment variables are set correctly in the container
fixes #735

integration/docker: set and check environment variables in the container

---

integration/docker/run_test.go

this patch improves hotplug test to hotplug 10 devices in a
container and checks they were hotplugged correctly
fixes #752

integration/docker: improve hotplug test

---

Makefile
conformance/posixfs/fstest.bats

This new test checks if the container's filesystem supports
most common filesystem operations
fixes #750

conformance/posixfs: Add posix filesystem conformance test

---

metrics/storage/fio_job.sh

Whilst running the storage (fio) tests, also measure the CPU
consuption and the memory footprint being used.
To do this we re-structure the test to set up the initial
test environment (get the container up and then init the
test file - which takes longer than the test itself), and then
we can know exactly when we are running the actual test.
Fixes: #630

metrics: storage: measure cpu and memory as well as bandwidth

---

metrics/network/remote_network/README.md
metrics/network/remote_network/remote-networking-cpu.sh
metrics/network/remote_network/remote-networking-test-common.sh

Add remote cpu consumption test while running an iperf3 bandwidth test.
Fixes #763

metrics: Add remote cpu consumption test.

---

metrics/network/network-metrics-iperf3.sh

Now the gabyct/network image has an updated iperf3 version, use
TMPDIR to point to the /dev/shm tmpfs rather than using the
tmpfs `mount` workaround (which no longer works as the container
is now more locked down).
Fixes: #779

metrics: network: iperf3: use TMPDIR to avoid 9p unlink issue

---

metrics/network/remote_network/remote-networking-cpu.sh
metrics/network/remote_network/remote-networking-iperf3.sh
metrics/network/remote_network/remote-networking-memory-smem.sh
metrics/network/remote_network/remote-networking-qperf.sh
metrics/network/remote_network/remote-networking-test-common.sh

Add init_env and init_env_remote functions with the purpose of ensure a clean testing environment.
Add check_images function to retrieve the latest of the image from Docker Hub.
Changes to the main functions exit codes as well error messages.

metrics: Changes to the remote networking tests

---

metrics/network/remote_network/remote-networking-memory-smem.sh

Add PSS remote networking memory using smem tool while running
iperf3 bandwidth test.
Fixes #792

metrics: Add PSS remote networking memory

---

docker.go
integration/docker/cap_test.go
integration/docker/main_test.go

This test adds or drops different capabilities.
Fixes #756

tests: Add docker --cap-add and --cap-drop test.

---

Makefile
integration/docker/package_manager_test.go

This test will perform a dnf update in a fedora container.
Fixes #803

tests: Add dnf update test for docker integration.

---

integration/docker/exec_test.go

Add some new ginkgo integration tests to ensure
`docker exec --user= ...` works as expected.
Fixes #805.

integration: Add tests for "docker exec --user"

---

docker.go
integration/docker/top_test.go

This tests the docker top functionality.
Fixes #812

tests: Add docker top integration test.

---

.ci/install_runtime.sh
.ci/openshift_setup.sh
.ci/setup_env_fedora.sh
.ci/setup_env_ubuntu.sh
cmd/container-manager/manage_ctr_mgr.sh

This PR:
- adds `manage_ctr_mgr.sh`.
- call manage_ctr_mgr.sh script in the CI scripts

add manage_ctr_mgr.sh tool

---

integration/docker/run_test.go

this test ensures CPU quota and period are honoured
fixes #821

integration/docker: Add CPU constraint test

---

integration/docker/run_test.go

This test will verify stdout and stderr using docker run.
Fixes #844

tests: Add docker run integration test for stdout and stderr.

---

.ci/install_clearcontainers_kernel.sh

If someone install too many times the kernel will have a github
block for non using a token.
Fixes: #852

ci: dont get latest kernel version from github api

---

command.go
docker.go
integration/docker/run_test.go

Test stdin while running docker run.
Fixes #853

tests: Add docker run with stdin.

---

.ci/jenkins_job_build.sh
.ci/setup.sh

Fix path to manage_ctr_mgr.sh
Fixes: #907

ci: jenkins: fix path to manage_ctr_mgr.sh
